# Generated by Django 3.0.7 on 2020-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateTimeField()),
                ('posting_date', models.DateTimeField()),
                ('material', models.IntegerField()),
                ('material_description', models.CharField(max_length=200)),
                ('movement_type', models.CharField(max_length=10)),
                ('cqe_1', models.IntegerField()),
                ('cqe_2', models.IntegerField()),
                ('que_1', models.FloatField()),
                ('que_2', models.FloatField()),
                ('ue', models.CharField(max_length=10)),
                ('alc_1', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('week', models.IntegerField()),
                ('alc_2', models.FloatField()),
            ],
        ),
    ]
