# Generated by Django 3.0.7 on 2020-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='plant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='production',
            name='material',
            field=models.CharField(max_length=200),
        ),
    ]
